server:
  port: 8088
spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/community
    data-username: root
    data-password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
